services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # This is the only change
    env_file:
      - .env
      # Run a command against the development stage of the image
    command: npm run start:debug
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis
    networks:
      - webnet
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    hostname: ${DB_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
networks:
  webnet:
volumes:
  pgdata:
  redis:
    driver: local
